<script setup lang="ts">
import { computed, ref, watch, onUnmounted } from "vue"

import { useConversationState } from "@/features/agent-chat/composables/useConversationState"
import { usePipChat } from "@/features/agent-chat/composables/usePipChat"
import { usePipEndConfirm } from "@/features/agent-chat/composables/usePipEndConfirm"
import { usePipIdleTimer } from "@/features/agent-chat/composables/usePipIdleTimer"
import { useProcessingFuse, useThinkingFuse } from "@/features/agent-chat/composables/usePipTurnFuses"
import { usePipVoiceReveal } from "@/features/agent-chat/composables/usePipVoiceReveal"
import { useWebRTC } from "@/features/agent-chat/composables/useWebRTC"

import PipChatPanel from "./PipChatPanel.vue"
import PipFrame from "./PipFrame.vue"
import { PIP_SIZES, type PipCorner, type PipSize } from "../types"

const props = defineProps<{ open: boolean }>()
const emit = defineEmits<{ close: [] }>()

const corner = ref<PipCorner>("br")
const size = ref<PipSize>("lg")
const moveMode = ref(false)
const settingsMode = ref(false)

const suppressTts = ref(false)

// Single source of truth for the voice conversation phase — see
// useConversationState for the transition table and defensive handling.
const conversation = useConversationState()

// ---- Idle timer: 45s of no activity -> warning card w/ 15s countdown ->
// zero closes. Any voice event or touch (see markActivity) cancels and
// returns to the prior state.
const {
  showIdleWarning,
  idleWarnSecondsLeft,
  resetIdleTimer,
  clearIdleTimer,
  clearIdleWarnInterval,
  dismissIdleWarning,
  markActivity,
} = usePipIdleTimer(() => emit("close"))

// ---- End-of-conversation confirm card. Backend emits `end_conversation` at
// tool-round time — the spoken farewell is generated by the *next* LLM round,
// so the event almost always arrives while we're still in `thinking` (or
// `processing`/`speaking`). Two timings to cover:
//   - mid-turn (thinking/processing/userSpeaking/speaking): park it and wait
//     for bot_silent so the card never covers or cuts off the farewell audio;
//     the thinking-fuse / TTS-watchdog fallbacks surface it if audio dies.
//   - late (already back to `listening`): show immediately.
const {
  showEndConfirm,
  endConfirmSecondsLeft,
  resolvePending: resolvePendingEndConversation,
  onEndConversationEvent,
  dismissEndConfirm,
  confirmEndNow,
  continueConversation,
} = usePipEndConfirm({
  isListening: () => conversation.state.value === "listening",
  close: () => emit("close"),
  beforeShow: () => {
    clearIdleTimer()
    dismissIdleWarning()
  },
  onContinue: () => {
    conversation.setListening()
    resetIdleTimer()
  },
})

const {
  sessionId,
  messages,
  userInput,
  isSending,
  showChat,
  displayedAgentText,
  clearDisplayedText,
  ttsState,
  mouthAmplitude,
  ensureSession,
  sendMessage,
  handleKeydown,
  abortStream,
  endSession,
} = usePipChat(suppressTts, markActivity)

const lastUserText = ref("")

// ---- Voice reply turn model + TTS watchdog — see usePipVoiceReveal: single
// owner of the assistant voice bubble AND the avatar subtitle, char-by-char
// reveal synced to playback, and the 4s TTS-dead fallback.
const {
  beginVoiceTurn,
  stopReveal,
  revealSegment,
  applyParkedReply,
  resetVoiceReply,
  startTtsWatchdog,
  clearTtsWatchdog,
  parkReply,
  discardParkedReply,
  markAudioStarted,
  hasAudioStarted,
} = usePipVoiceReveal({
  messages,
  displayedAgentText,
  onWatchdogExpire: () => {
    conversation.forceListening()
    // If end_conversation already arrived (waiting on a bot_silent that will
    // never come because TTS died), surface the card now instead of never.
    if (!resolvePendingEndConversation()) resetIdleTimer()
  },
})

// 30s safety fuse: total-failure fallback if neither a reply nor a cancel
// ever arrives for a turn (distinct from the 4s TTS watchdog above, which
// only fires once a reply text already exists) — force back to listening
// rather than leaving the UI stuck in `thinking`.
const { start: startThinkingFuse, clear: clearThinkingFuse } = useThinkingFuse(() => {
  lastUserText.value = ""
  conversation.forceListening()
  // Same fallback as the TTS watchdog: a parked end_conversation must still
  // get its card even when the farewell turn silently died.
  if (!resolvePendingEndConversation()) resetIdleTimer()
})

// Processing fuse: `user_silent` -> `transcript` has no guaranteed follow-up —
// backend drops empty ASR results without emitting any event — so "辨識中…"
// could otherwise hang until the 45s idle path. Armed/cleared by watching the
// state itself: any transition out of `processing` (transcript, barge-in,
// error, reset) disarms it.
const { clear: clearProcessingFuse } = useProcessingFuse(conversation.state, () => {
  conversation.forceListening()
  resetIdleTimer()
})

onUnmounted(() => {
  clearIdleTimer()
  clearThinkingFuse()
  clearProcessingFuse()
  clearTtsWatchdog()
  clearIdleWarnInterval()
  dismissEndConfirm()
  stopReveal()
})

const {
  state: webrtcState,
  mouthAmplitude: webrtcAmplitude,
  connect: webrtcConnect,
  disconnect: webrtcDisconnect,
} = useWebRTC(
  {
    onTranscript: (text) => {
      // New user turn — the sole turn boundary. beginVoiceTurn freezes the
      // previous bubble and opens a fresh one, so nothing from the prior turn
      // can write here anymore.
      lastUserText.value = text
      clearDisplayedText()
      conversation.onTranscript()
      markActivity()
      startThinkingFuse()
      beginVoiceTurn(text)
    },
    onReply: (text) => {
      // Full-text signal — timing relative to playback varies. Always just park
      // it and arm the watchdog; subtitle/bot_speaking cancel the watchdog when
      // audio is really playing, bot_silent (normal) or the watchdog (TTS-dead)
      // applies it.
      clearThinkingFuse()
      lastUserText.value = ""
      markActivity()
      parkReply(text)
      startTtsWatchdog()
    },
    onCancelled: () => {
      // agent_cancelled (barge-in): stop the reveal and clear the parked reply
      // so the bubble stays at whatever was actually spoken — never flush the
      // full text the user cut off.
      clearThinkingFuse()
      lastUserText.value = ""
      conversation.onAgentCancelled()
      markActivity()
      clearTtsWatchdog()
      stopReveal()
      discardParkedReply()
    },
    onSubtitle: (text, durationMs) => {
      // Fires as each TTS segment starts playing — reveals over durationMs so
      // the bubble tracks playback pace. Audio is alive: the TTS-dead watchdog
      // no longer applies, and this turn is now flushable on bot_silent.
      clearTtsWatchdog()
      // Audio is confirmed playing — same signal onBotSpeaking uses to disarm
      // the 30s thinking fuse. Without this, a reply whose onReply/onBotSpeaking
      // never fires (or fires >30s after the transcript) gets its playback cut
      // by the fuse forcing back to listening mid-speech.
      clearThinkingFuse()
      markAudioStarted()
      conversation.onSubtitle()
      markActivity()
      revealSegment(text, durationMs)
    },
    onBotSpeaking: () => {
      // TTS audio is actively playing — pause the idle clock entirely (not
      // just reschedule) so long replies don't get killed mid-playback.
      clearTtsWatchdog()
      clearThinkingFuse()
      markAudioStarted()
      conversation.onBotSpeaking()
      clearIdleTimer()
      dismissIdleWarning()
    },
    onBotSilent: () => {
      clearTtsWatchdog()
      // Trailing bot_silent from a previous (e.g. barged-in) turn: the current
      // turn hasn't produced any audio yet, so this can't be ours — drop it
      // instead of stopping our reveal / flushing / resetting the idle clock.
      if (!hasAudioStarted()) return
      stopReveal()
      applyParkedReply()
      conversation.onBotSilent()
      if (!resolvePendingEndConversation()) resetIdleTimer()
    },
    onUserSpeaking: () => {
      // User spoke while the end-confirm card was up — they clearly want to
      // keep going; treat it as pressing「閣繼續問」so the 10s countdown can't
      // close the PiP mid-sentence.
      if (showEndConfirm.value) dismissEndConfirm()
      conversation.onUserSpeaking()
      markActivity()
    },
    onUserSilent: () => {
      conversation.onUserSilent()
      markActivity()
    },
    onEndConversation: onEndConversationEvent,
  },
  // Share the existing chat session so voice and text have the same conversation context.
  sessionId,
)


// Use WebRTC audio amplitude when connected, otherwise TTS amplitude
const activeMouthAmplitude = computed(() =>
  webrtcState.value === "connected" ? webrtcAmplitude.value : mouthAmplitude.value
)

watch(
  webrtcState,
  (state) => {
    suppressTts.value = state === "connected" || state === "connecting"
    if (state === "connecting") conversation.setConnecting()
    else if (state === "connected") {
      conversation.setListening()
      resetIdleTimer()
    } else if (props.open) {
      // "error", or an unexpected "disconnected" while the PiP is still open
      // (deliberate close paths flip props.open false *before* disconnecting,
      // so they never reach here). Freeze into the static error visual and
      // kill every event-driven timer — no data-channel event can arrive to
      // resolve them. The idle timer stays armed as the automatic exit next
      // to the always-visible end button.
      conversation.setError()
      clearThinkingFuse()
      clearProcessingFuse()
      clearTtsWatchdog()
      dismissEndConfirm()
      resetIdleTimer()
    }
  },
  { immediate: true }
)

watch(
  () => props.open,
  async (open) => {
    if (open) {
      conversation.reset()
      if (webrtcState.value === "connecting") webrtcDisconnect()
      if (webrtcState.value !== "connected") {
        // Suppress REST TTS before ensureSession: the voice pipeline owns the
        // welcome greeting. Without this the welcome is spoken twice (REST +
        // WebRTC). The webrtcState watcher takes over after connect starts.
        suppressTts.value = true
        await ensureSession() // wait for session before sending offer (ensureSession never throws)
        if (!props.open) return // closed while awaiting session
        void webrtcConnect()
      }
    } else {
      // Single teardown, fixed order:
      //   1. abort the in-flight text stream (backend discards the partial turn)
      //   2. disconnect WebRTC → backend on_client_disconnected → pipeline task.cancel
      //   3. DELETE the chat session (idempotent server-side) + clear local state
      abortStream()
      webrtcDisconnect()
      endSession() // cancels TTS, clears messages + displayedAgentText, deletes session

      moveMode.value = false
      settingsMode.value = false
      lastUserText.value = ""
      resetVoiceReply()
      clearThinkingFuse()
      clearProcessingFuse()
      clearTtsWatchdog()
      clearIdleTimer()
      dismissIdleWarning()
      dismissEndConfirm()
      conversation.reset()
    }
  },
)

const frameSize = computed(() => PIP_SIZES[size.value])

function selectCorner(next: PipCorner) {
  corner.value = next
  moveMode.value = false
}

function enterMoveFromSettings() {
  settingsMode.value = false
  moveMode.value = true
}

function openChatFromSettings() {
  settingsMode.value = false
  showChat.value = true
}

// Class-based positioning — Tailwind utilities derived from corner. Avoids inline-style reactivity issues with Transition.
const posClass = computed(() => {
  switch (corner.value) {
    case "tl": return "top-5 left-5"
    case "tr": return "top-5 right-5"
    case "bl": return "bottom-5 left-5"
    case "br": return "bottom-5 right-5"
  }
})
const dirClass = computed(() =>
  corner.value.endsWith("r") ? "flex-row-reverse" : "flex-row",
)
</script>

<template>
  <Transition
    enter-active-class="transition-[opacity,transform] duration-200"
    enter-from-class="opacity-0 scale-95"
    leave-active-class="transition-[opacity,transform] duration-200"
    leave-to-class="opacity-0 scale-95"
  >
    <div
      v-if="open"
      class="fixed z-[9999] flex gap-3 items-end max-w-[calc(100vw-40px)]"
      :class="[posClass, dirClass]"
      @pointerdown.capture="markActivity"
    >
      <Transition
        enter-active-class="transition-[opacity,transform] duration-[180ms]"
        enter-from-class="opacity-0 translate-x-2"
        leave-active-class="transition-[opacity,transform] duration-[180ms]"
        leave-to-class="opacity-0 translate-x-2"
      >
        <PipChatPanel
          v-if="showChat"
          v-model:user-input="userInput"
          :messages="messages"
          :is-sending="isSending"
          :height-px="frameSize.h"
          @close="showChat = false"
          @send="sendMessage"
          @keydown="handleKeydown"
        />
      </Transition>

      <PipFrame
        :width="frameSize.w"
        :height="frameSize.h"
        :size="size"
        :last-agent-text="displayedAgentText"
        :is-sending="isSending"
        :show-chat="showChat"
        :conversation-state="conversation.state.value"
        :tts-state="ttsState"
        :mouth-amplitude="activeMouthAmplitude"
        :last-user-text="lastUserText"
        :move-mode="moveMode"
        :settings-mode="settingsMode"
        :corner="corner"
        :show-end-confirm="showEndConfirm"
        :end-confirm-seconds-left="endConfirmSecondsLeft"
        :show-idle-warning="showIdleWarning"
        :idle-warn-seconds-left="idleWarnSecondsLeft"
        @close="emit('close')"
        @toggle-settings="settingsMode = !settingsMode"
        @cancel-settings="settingsMode = false"
        @set-size="size = $event"
        @enter-move="enterMoveFromSettings"
        @open-chat="openChatFromSettings"
        @select-corner="selectCorner"
        @cancel-move="moveMode = false"
        @confirm-end="confirmEndNow"
        @continue-conversation="continueConversation"
        @dismiss-idle-warning="() => { dismissIdleWarning(); resetIdleTimer() }"
      />
    </div>
  </Transition>
</template>
