import { ref } from "vue"

// Backend emits `end_conversation` at tool-round time — the spoken farewell
// is generated by the *next* LLM round, so the event almost always arrives
// while we're still in `thinking` (or `processing`/`speaking`). Two timings
// to cover:
//   - mid-turn: park it and wait for `bot_silent` (see `resolvePending`) so
//     the card never covers or cuts off the farewell audio; the
//     thinking-fuse / TTS-watchdog fallbacks resolve it if audio dies.
//   - late (already back to `listening`): show immediately.
const END_CONFIRM_COUNTDOWN_S = 10

/**
 * End-of-conversation confirm card: shown either immediately (state is
 * already `listening`) or parked until the caller calls `resolvePending()`
 * once the farewell has finished playing.
 */
export function usePipEndConfirm(deps: {
  /** Whether the voice conversation is currently idle (safe to show now). */
  isListening: () => boolean
  /** Countdown hit zero without a response — closes the PiP. */
  close: () => void
  /** Called right before the card becomes visible (e.g. pause the idle timer). */
  beforeShow: () => void
  /** User chose to keep talking — resume normal idle tracking. */
  onContinue: () => void
}) {
  const showEndConfirm = ref(false)
  const endConfirmSecondsLeft = ref(END_CONFIRM_COUNTDOWN_S)
  let endConfirmInterval: number | null = null
  let endConversationPending = false

  function clearEndConfirmInterval() {
    if (endConfirmInterval !== null) { clearInterval(endConfirmInterval); endConfirmInterval = null }
  }

  function showEndConversationCard() {
    deps.beforeShow()
    showEndConfirm.value = true
    endConfirmSecondsLeft.value = END_CONFIRM_COUNTDOWN_S
    clearEndConfirmInterval()
    endConfirmInterval = window.setInterval(() => {
      endConfirmSecondsLeft.value -= 1
      if (endConfirmSecondsLeft.value <= 0) {
        clearEndConfirmInterval()
        deps.close()
      }
    }, 1000)
  }

  /** Show the parked end-conversation card, if any. Returns whether it did. */
  function resolvePending(): boolean {
    if (!endConversationPending) return false
    endConversationPending = false
    showEndConversationCard()
    return true
  }

  function onEndConversationEvent() {
    if (deps.isListening()) {
      showEndConversationCard()
    } else {
      endConversationPending = true
    }
  }

  function dismissEndConfirm() {
    clearEndConfirmInterval()
    showEndConfirm.value = false
    endConversationPending = false
  }

  function confirmEndNow() {
    clearEndConfirmInterval()
    showEndConfirm.value = false
    deps.close()
  }

  function continueConversation() {
    dismissEndConfirm()
    deps.onContinue()
  }

  return {
    showEndConfirm,
    endConfirmSecondsLeft,
    resolvePending,
    onEndConversationEvent,
    dismissEndConfirm,
    confirmEndNow,
    continueConversation,
    clearEndConfirmInterval,
  }
}
