import { ref } from "vue"

import {
  currentSynchronousScopeReleaseAttempt,
  observeSynchronousScopeTeardown,
  runWithSynchronousScopeReleaseAttempt,
} from "@/lib/component-lifecycle"
import {
  createResourceOwner,
  type ResourceReleaseAttempt,
} from "@/lib/resource-owner"
import { createOwnedInterval, type TimerLease } from "@/lib/timer-owner"

// Backend emits `end_conversation` at tool-round time — the spoken farewell
// is generated by the *next* LLM round, so the event almost always arrives
// while we're still in `thinking` (or `processing`/`speaking`). Two timings
// to cover:
//   - mid-turn: park it and wait for `bot_silent` (see `resolvePending`) so
//     the card never covers or cuts off the farewell audio; the
//     thinking-fuse / TTS-watchdog fallbacks resolve it if audio dies.
//   - late (already back to `listening`): show immediately.
const END_CONFIRM_COUNTDOWN_S = 10

function throwFailures(failures: unknown[], message: string): void {
  if (failures.length === 1) throw failures[0]
  if (failures.length > 1) throw new AggregateError(failures, message)
}

/**
 * End-of-conversation confirm card: shown either immediately (state is
 * already `listening`) or parked until the caller calls `resolvePending()`
 * once the farewell has finished playing.
 */
export function usePipEndConfirm(deps: {
  /** Whether the voice conversation is currently idle (safe to show now). */
  isListening: () => boolean
  /** Countdown hit zero without a response — closes the PiP. */
  close: () => void
  /** Called right before the card becomes visible (e.g. pause the idle timer). */
  beforeShow: () => void
  /** User chose to keep talking — resume normal idle tracking. */
  onContinue: () => void
}) {
  const showEndConfirm = ref(false)
  const endConfirmSecondsLeft = ref(END_CONFIRM_COUNTDOWN_S)
  const owner = createResourceOwner("PiP end confirmation")
  let countdownInterval: TimerLease | null = null
  let countdownGeneration = 0
  let endConversationPending = false

  function runOperation<T>(
    operation: (attempt: ResourceReleaseAttempt) => T,
  ): T {
    const attempt = currentSynchronousScopeReleaseAttempt() ?? {}
    return runWithSynchronousScopeReleaseAttempt(
      attempt,
      () => operation(attempt),
    )
  }

  function closeAfterSetupFailure(
    setupError: unknown,
    attempt: ResourceReleaseAttempt,
  ): never {
    try {
      owner.dispose(attempt)
    } catch (cleanupError) {
      throw new AggregateError(
        [setupError, cleanupError],
        "Failed to initialize and close PiP end confirmation countdown",
      )
    }
    throw setupError
  }

  function stopCountdown(attempt: ResourceReleaseAttempt): void {
    countdownGeneration++
    const current = countdownInterval
    if (!current) return
    current.cancel(attempt)
    if (!current.active && countdownInterval === current) {
      countdownInterval = null
    }
  }

  function clearEndConfirmStateWithAttempt(
    attempt: ResourceReleaseAttempt,
  ): void {
    showEndConfirm.value = false
    endConversationPending = false
    stopCountdown(attempt)
  }

  function confirmEndNowWithAttempt(attempt: ResourceReleaseAttempt): void {
    const shouldClose = !owner.disposed
    const failures: unknown[] = []
    try {
      clearEndConfirmStateWithAttempt(attempt)
    } catch (error) {
      failures.push(error)
    }
    if (shouldClose) {
      try {
        runWithSynchronousScopeReleaseAttempt(attempt, deps.close)
      } catch (error) {
        failures.push(error)
      }
      if (owner.disposed && !owner.settled) {
        failures.push(
          new Error("PiP end confirmation cleanup remains unresolved"),
        )
      }
    }
    throwFailures(failures, "Failed to confirm PiP conversation end")
  }

  function showEndConversationCardWithAttempt(
    attempt: ResourceReleaseAttempt,
  ): boolean {
    if (owner.disposed) return false
    runWithSynchronousScopeReleaseAttempt(attempt, deps.beforeShow)
    if (owner.disposed) return false
    stopCountdown(attempt)
    showEndConfirm.value = true
    endConfirmSecondsLeft.value = END_CONFIRM_COUNTDOWN_S

    const generation = ++countdownGeneration
    let next: TimerLease
    try {
      next = createOwnedInterval(
        owner,
        "PiP end confirmation interval",
        callbackAttempt => {
          if (owner.disposed || countdownGeneration !== generation) return false
          endConfirmSecondsLeft.value -= 1
          if (endConfirmSecondsLeft.value > 0) return true
          confirmEndNowWithAttempt(callbackAttempt)
          return false
        },
        1000,
        attempt,
      )
    } catch (setupError) {
      if (countdownGeneration === generation) countdownGeneration++
      return closeAfterSetupFailure(setupError, attempt)
    }

    if (
      !owner.disposed
      && countdownGeneration === generation
      && next.active
    ) {
      countdownInterval = next
    } else if (next.active) {
      next.cancel(attempt)
    }
    return true
  }

  /** Show the parked end-conversation card, if any. Returns whether it did. */
  function resolvePending(): boolean {
    return runOperation(attempt => {
      if (owner.disposed || !endConversationPending) return false
      endConversationPending = false
      return showEndConversationCardWithAttempt(attempt)
    })
  }

  function onEndConversationEvent(): void {
    runOperation(attempt => {
      if (owner.disposed) return
      const listening = runWithSynchronousScopeReleaseAttempt(
        attempt,
        deps.isListening,
      )
      if (owner.disposed) return
      if (listening) showEndConversationCardWithAttempt(attempt)
      else endConversationPending = true
    })
  }

  function dismissEndConfirm(): void {
    runOperation(clearEndConfirmStateWithAttempt)
  }

  function confirmEndNow(): void {
    runOperation(confirmEndNowWithAttempt)
  }

  function continueConversation(): void {
    runOperation(attempt => {
      const shouldContinue = !owner.disposed
      const failures: unknown[] = []
      try {
        clearEndConfirmStateWithAttempt(attempt)
      } catch (error) {
        failures.push(error)
      }
      if (shouldContinue) {
        try {
          runWithSynchronousScopeReleaseAttempt(attempt, deps.onContinue)
        } catch (error) {
          failures.push(error)
        }
      }
      throwFailures(failures, "Failed to continue PiP conversation")
    })
  }

  observeSynchronousScopeTeardown("PiP end confirmation teardown", attempt => {
    countdownGeneration++
    showEndConfirm.value = false
    endConversationPending = false
    owner.dispose(attempt)
    if (!owner.settled) {
      throw new Error("PiP end confirmation cleanup remains unresolved")
    }
    countdownInterval = null
  })

  return {
    showEndConfirm,
    endConfirmSecondsLeft,
    resolvePending,
    onEndConversationEvent,
    dismissEndConfirm,
    confirmEndNow,
    continueConversation,
  }
}
